# Generated by Django 4.2.25 on 2025-10-29 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_profile_access_token_profile_display_name_and_more'),
        ('app_home', '0013_postimage_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app_home.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='app_users.profile')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
