# Generated by Django 4.2.25 on 2025-10-30 05:17

import core.settings.content_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0014_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to=core.settings.content_path.UserContentPath('post_media', include_date=True)),
        ),
    ]
