# Generated by Django 4.2.25 on 2025-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0015_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
